
name: Prisma Cloud Compute Image Scan

on: [push, pull_request]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  

jobs:
  # Jobs are ran independently from each other, so build and scan needs to be in a single job.
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        # Defaults are sufficient generally
        # https://github.com/actions/checkout#usage
    #  - name: Build the image
   #     run: docker build -t $IMAGE_NAME .
      - name: test the directory
        run: ls
      - name: Scan the image
        env:
          PCC_USER: ${{ secrets.PCC_USER }}
          PCC_PASS: ${{ secrets.PCC_PASS }}
        run: |
          echo "Username is: ${{ secrets.PCC_USER }}"
          TL_USER=${{ secrets.PCC_USER }}
          TL_PASSWORD=${{ secrets.PCC_PASS }}
          wget --header "Authorization: Basic $(echo -n $TL_USER:$TL_PASSWORD | base64 | tr -d '\n')" "$TL_CONSOLE/api/v1/util/twistcli"
          chmod a+x ./twistcli
          ./twistcli images scan --address "https://us-east1.cloud.twistlock.com/us-2-158256885" -u $TL_USER -p $TL_PASSWORD --details $IMAGE_NAME
